apiVersion: v1
kind: Service
metadata:
  name: kudocad-service
spec:
  selector:
    app: kudocad
  ports:
  - name: service-port
    protocol: TCP
    port: 80
    targetPort: kudocad-port
  type: LoadBalancer
